services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sensorygroove
      - WPP_API_URL=http://wppconnect:21465
      - WPP_SECRET_KEY=sensory_secret_token_123
      - ADMIN_USER=admin
      - ADMIN_PASS=sensory_2026
      - ADMIN_WA_NUMBER_1=5216142550381
      - ADMIN_WA_NUMBER_2=5216142854941
    depends_on:
      - db
      - wppconnect
    volumes:
      - ./backend/uploads:/app/uploads

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sensorygroove
    volumes:
      - pgdata:/var/lib/postgresql/data

  wppconnect:
    image: wppconnect/wppconnect-server:latest
    ports:
      - "21465:21465"
    environment:
      - SECRET_KEY=sensory_secret_token_123
    volumes:
      - wppdata:/home/node/app/tokens

volumes:
  pgdata:
  wppdata:
